version: "3"

services:

  web:
    build: ./web
    container_name: tmdb-web
    ports:
      - "9090:9090"
    environment:
      BACKEND_SERVICE_HOST: tmdb-server
      BACKEND_SERVICE_PORT: 9000

  server:
    build: ./server
    container_name: tmdb-server
    ports:
      - "9000:9000"
    env_file:
      - server/server.env
      - server/secrets.env
